# Clone, create branch, move folders, commit changes
# See see https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# TODO: 
# 2. Specify branch name to use?
# 3. Output the link to the branch?
#

name: 'Test phpBB Extension in Codespaces'
description: 'This action creates the necessary setup files to test a phpBB extension in a Codespace with both phpBB and the extension to be pre-installed.'

inputs:
  source-branch:
    description: 'phpBB branch to use'
    required: true
    default: '3.3.x'
  destination-branch:
    description: 'New branch to create in the extension project (timestamp will be appended)'
    required: true
    default: 'codespace-test'

# TODO: refine this to certain actions
#on:
#  workflow_dispatch:
#    inputs:
#      branch_name:
#        description: 'Name of the new branch'
#        required: true
#        default: 'codespaces/2024-10-06-test'

runs:
  using: "composite"
  steps:
  - name: Checkout current repository
    uses: actions/checkout@v4
  # Clone phpBB so we can use most of the same Codespace configuration as the main project
  - name: Clone external phpBB repository
    shell: bash
    env:
     INPUT_SOURCE_BRANCH: ${{ inputs.source-branch }}
    run: |
      sudo mkdir -p /workspace/phpbb
      sudo git clone -b "$INPUT_SOURCE_BRANCH" --single-branch https://github.com/phpbb/phpbb.git /workspace/phpbb
  # Move the Codespaces configuration into the user project
  - name: Move Codespaces files back to the current repository
    shell: bash
    run: |
      sudo mv /workspace/phpbb/.devcontainer .devcontainer
      sudo mv /workspace/phpbb/.vscode .vscode
  # Open composer.json from the user package, extract the name from the 'name' key and then use
  # that to create the Codespace configuration and have the extension auto-install.
  - name: Adjust extension name in setup, launcher and installer
    shell: bash
    run: |
      EXT_NAME=$(jq .name composer.json)
      EXT_NAME_STRIPPED=$(echo $EXT_NAME | awk -F '/' '{print $NF}' | tr -d '"')
      echo "EXTENSION_NAME=$(echo $EXT_NAME_STRIPPED)" >> $GITHUB_ENV

      sed -i "s/PHPBB_EXTENSION_NAME/$EXT_NAME_STRIPPED/g" "${{ github.action_path }}/setup.sh"

      sudo sed -i "s/\/var\/www\/html/\/var\/www\/html\/ext\/phpbb\/$EXT_NAME_STRIPPED/g" .vscode/launch.json
      sudo sed -i "s/\/phpBB\//\//g" .vscode/launch.json

      sudo sed -i "s/\[\]/\[${EXT_NAME//\//\\/}\]/g" .devcontainer/resources/phpbb-config.yml
  # Use setup.sh from the GitHub Action because it is tailored for an extension
  - name: Copy a custom setup.sh file
    shell: bash
    run: |
      sudo rm -rf .devcontainer/resources/setup.sh
      cat "${{ github.action_path }}/setup.sh" | sudo tee '.devcontainer/resources/setup.sh' > '/dev/null'
  # Create a new branch for the user to create the Codespace on GitHub so it doesn't impact the main project
  - name: Save to a new branch
    shell: bash
    env:
      INPUT_DESTINATION_BRANCH: ${{ inputs.destination-branch }}
    run: |
      BRANCH_NAME="$INPUT_DESTINATION_BRANCH/$(date +%Y%m%d%H%M)"
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git config user.name "github-actions[bot]"
      git checkout -b "$BRANCH_NAME"
      git add .
      git commit -m "Codespaces setup"
      git push -u origin "$BRANCH_NAME"
