# Clone, create branch, move folders, commit changes
# See see https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# TODO: Specify phpbb branch?
name: Test phpBB Extension in Codespaces

# TODO: refine this to certain actions
#on:
#  workflow_dispatch:
#    inputs:
#      branch_name:
#        description: 'Name of the new branch'
#        required: true
#        default: 'codespaces/2024-10-06-test'

runs:
  using: "composite"
  steps:
  - name: Checkout current repository
    uses: actions/checkout@v4
  - name: Clone external phpBB repository
    shell: bash
    run: |
      sudo mkdir -p /workspace/phpbb
      sudo git clone -b 3.3.x --single-branch  https://github.com/phpbb/phpbb.git /workspace/phpbb
  - name: Move Codespaces files back to the current repository
    shell: bash
    run: |
      sudo mv /workspace/phpbb/.devcontainer .devcontainer
      sudo mv /workspace/phpbb/.vscode .vscode
  # Don't use ${{ github.event.inputs.branch_name }} codespaces/test-${{ env.NOW_DATE }} yet
  - name: Save to a new branch
    shell: bash
    run: |
      echo "NOW_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      git config user.email "github-actions[bot]@users.noreply.github.com"
      git config user.name "github-actions[bot]"
      git add .
      git commit -m "Codespaces setup"
      git checkout -b codespaces/test-$(date +%Y%m%d%H%M)
      git push origin codespaces/test-$(date +%Y%m%d%H%M)
